# Generated by Django 3.1.4 on 2021-01-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210121_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookShop',
        ),
    ]
