# Generated by Django 3.1.4 on 2021-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210119_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshop',
            name='year',
        ),
        migrations.AlterField(
            model_name='bookshop',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
