# Generated by Django 3.1.4 on 2021-01-22 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bookshop_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshop',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookshop',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 14, 45, 33, 740068)),
        ),
    ]
