# Generated by Django 3.1.4 on 2021-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210119_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshop',
            name='year',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='bookshop',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
