# Generated by Django 3.1.4 on 2021-01-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210119_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='description',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='bookshop',
            name='genres',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='bookshop',
            name='subtitle',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='bookshop',
            name='text',
            field=models.CharField(max_length=140),
        ),
    ]
