# Generated by Django 3.1.4 on 2021-01-22 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210122_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookshop',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 14, 52, 54, 23317)),
        ),
    ]
