# Generated by Django 3.1.4 on 2021-01-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210119_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshop',
            name='price',
        ),
    ]
