# Generated by Django 3.1.4 on 2021-01-23 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210122_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshop',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookshop',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 7, 3, 7026)),
        ),
    ]
