# Generated by Django 3.1.4 on 2021-01-23 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210123_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 48, 54, 851271)),
        ),
    ]
