# Generated by Django 3.1.4 on 2021-01-23 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210123_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 2, 18, 14, 250240)),
        ),
    ]
