# Generated by Django 3.1.4 on 2021-01-24 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210124_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 21, 48, 57, 456270)),
        ),
    ]
